# Generated by Django 4.0.3 on 2022-08-06 19:45

from django.db import migrations
from webapp.models import RoomProfileRole


def create_student(apps, schema_editor):
    role = RoomProfileRole()
    role.name = "Student"
    role.save()

def create_mentor(apps, schema_editor):
    role = RoomProfileRole()
    role.name = "Mentor"
    role.save()

def create_super_mentor(apps, schema_editor):
    role = RoomProfileRole()
    role.name = "Super Mentor"
    role.save()

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_summary_options'),
    ]

    operations = [
        migrations.RunPython(create_student, migrations.RunPython.noop),
        migrations.RunPython(create_mentor, migrations.RunPython.noop),
        migrations.RunPython(create_super_mentor, migrations.RunPython.noop)
    ]
