# Generated by Django 4.0.3 on 2022-08-06 19:45

from django.db import migrations
from webapp.models import RoomProfileRole


def create_roles(apps, schema_editor):
    RoomProfileRole.objects.bulk_create([
        RoomProfileRole(id=1, name="Student"),
        RoomProfileRole(id=2, name="Mentor"),
        RoomProfileRole(id=3, name="Super Mentor"),
    ])

class Migration(migrations.Migration):
    
    dependencies = [
        ('webapp', '0002_alter_summary_options'),
    ]

    operations = [
        migrations.RunPython(create_roles, migrations.RunPython.noop),
    ]
